apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    app: pod1-label
    tir: backend
spec:
  containers:
  - name: pod-nginx
	image: docker.io/nginx
    ports:
    - name: http80
      containerPort: 80
      hostPort: 80